import type { Bot } from '../types'

export const BOTS = [
  {
    id: 'honest' as const,
    name: 'Mehmet Yılmaz',
    title: 'Güvenilir Tüccar',
    contractType: 'İkili Ticaret Sözleşmesi',
    contractRef: 'TBK md.207',
    loanRepayRate: 0.82,
    loanAmount: 80,
    emoji: '🤝',
    color: '#00d4aa',
    colorRgb: '0,212,170',
    risk: 'Düşük Risk',
    riskColor: '#00d4aa',
    basePrice: 200,
    baseReward: 240,
    baseSuccessRate: 0.82,
    delay: 1800,
    catchphrase: 'Söz verdiysem yerine getiririm.',
    description: 'Niyeti dürüst, kâr marjı düşük. Piyasa şokları onu da sarsar.',
    riskTolerance: 0.9,
    priceFlexibility: 0.05,
    failureType: 'force_majeure' as const,
    dialogues: {
      greet:       ['Biz yaşlı adamız, ne anlarız bu otomatik sözleşme denen şeyden…', 'Evlat, ben sözümün eri bir adamım.'],
      smart:       ['Koşullu ifa sözleşmesi mi? Tamam tamam, imzalıyorum.', 'Bilgisayarlar benim yerime mi konuşacak şimdi?'],
      success:     ['Gördün mü? Söz verdiysem yerine getiririm.', 'İşte bu. Ticaret böyle yapılır.'],
      fail:        ['Allah\'ım, ben de bilmiyordum…', 'Çocuk, bu benim elimde değildi.'],
      loanRequest: ['Sıkışık durumdayım. Küçük bir yardım… Geri öderim tabii.', 'Güvenin bana — her zaman sözümün eri oldum.'],
      loanRepay:   ['İşte paranız — faizli. Güveni kötüye kullanmadım.', 'Söz vermiştim. Aldığınız gibi geri verdim.'],
      loanDefault: ['Allah\'ım, elim ayağım tutmuyor. Dava açarsanız anlayışla karşılarım.', 'Elimde değildi. Ama haklarınızı ararsanız anlayış gösteririm.'],
    },
  },
  {
    id: 'opportunist' as const,
    name: 'Kerem Aslan',
    title: 'Bağımsız Ajan',
    contractType: 'Hizmet Sözleşmesi',
    contractRef: 'TBK md.386',
    loanRepayRate: 0.25,
    loanAmount: 60,
    emoji: '🦊',
    color: '#ff6b35',
    colorRgb: '255,107,53',
    risk: 'Yüksek Risk',
    riskColor: '#ff4444',
    basePrice: 150,
    baseReward: 420,
    baseSuccessRate: 0.22,
    delay: 2800,
    catchphrase: 'Fiyat uygunsa… görüşürüz.',
    description: 'Sözleşmede açık bulursa teslim etmez. Başardığında kâr yüksek.',
    riskTolerance: 0.3,
    priceFlexibility: 0.25,
    failureType: 'fraud' as const,
    dialogues: {
      greet:       ['Para peşin, teslimat… zaman içinde olur.', 'Sözleşmeye bak, her şey yazıyor.'],
      smart:       ['Otomatik ifa ha? İade ediliyor… ilginç.', 'Şartlar çok sert ama bakabiliriz.'],
      success:     ['Görüyor musun? Ben de teslim ederim. Bazen.', 'Bugün şanslı günündü.'],
      fail:        ['Teknik sorunlar çıktı. Anlarsın.', '\'Makul süre\' diyordu. Ben de makul buldum.'],
      loanRequest: ['Kısa süreli bir nakit ihtiyacım var. Güvenilir bir teklif.', 'İş fırsatı çıktı. Yatırım dönecek sana.'],
      loanRepay:   ['İşte paran. Şaşırdın mı?', 'Bazı şeyleri geri öderim. Bugün öyle bir gün.'],
      loanDefault: ['Maalesef olmadı. Mahkemede görüşürüz.', 'Para gitti. Dava açarsan savcıya anlat.'],
    },
  },
  {
    id: 'contractor' as const,
    name: 'İbrahim Çelik',
    title: 'İnşaat & Proje Yöneticisi',
    contractType: 'Eser Sözleşmesi',
    contractRef: 'TBK md.470',
    loanRepayRate: 0.55,
    loanAmount: 100,
    emoji: '🏗️',
    color: '#3b82f6',
    colorRgb: '59,130,246',
    risk: 'Orta Risk',
    riskColor: '#f39c12',
    basePrice: 300,
    baseReward: 370,
    baseSuccessRate: 0.58,
    delay: 2400,
    catchphrase: 'Proje teslim edilir — ama inşaat gecikir, bu kanundur.',
    description: 'Büyük işler alır. Teslim etse de piyasa kârı eritiyor. Davası 10 yıl sürer.',
    riskTolerance: 0.5,
    priceFlexibility: 0.15,
    failureType: 'delay' as const,
    dialogues: {
      greet:       ['Taşınmaz işi budur, her şey kademeli ilerler.', 'Projemiz hazır, ruhsatlar tamam.'],
      smart:       ['Otomatik ifa, taşınmazlarda mı? İlginç.', 'Ruhsat gecikmesi de ceza kapsamında mı?'],
      success:     ['Proje teslim. Biraz geciktik ama teslim ettik.', 'İnşaat böyle bir şeydir.'],
      fail:        ['Belediye ruhsatı vermedi. Bizim elimizde değil.', 'Malzeme fiyatları üç katına çıktı.'],
      loanRequest: ['Nakit akışında geçici bir sorun var. Kısa vadeli borç.', 'Projeye malzeme alacağım. Geri ödeme garantiliyim.'],
      loanRepay:   ['Proje sattı, işte paranız.', 'Söz verdim, ödedim. İnşaat gecikir ama borç ödemez.'],
      loanDefault: ['Malzeme fiyatları patladı. Nakit yok. Dava açabilirsiniz.', 'Zor bir dönem. Hukuki yolları kullanın.'],
    },
  },
] satisfies Bot[]
